config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'chatroom/index'
  root 'chatroom#index'

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  post 'message', to: 'messages#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


    def current_user
        #this helper gives the name of the user who is logged in
        @current_user ||=User.find(session[:user_id]) if session[:user_id]#
    end
    
    
    def logged_in?
        #this helper will give the output as true or false
        #true-->user is logged in
        #false-->user is not logged in
        !!current_user#represents boolean


    
        
    end


    def require_user
        if !logged_in?
            redirect_to login_path
        end    

    end    


end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @message=Message.new
    @messages=Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def create
        #byebug
        message=current_user.messages.build(params.require(:message).permit(:body))
        message.save
        redirect_to root_path
        
    end       
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  def create
    user=User.find_by(username: params[:session][:username])#user=?
    if user && user.authenticate(params[:session][:password])
      session[:user_id]=user.id
      redirect_to root_path
    else
      redirect_to login_path  
    end  
    


    #byebug
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular orange coffee icon"></i>
  Friends
</h2>

<div class="ui two column grid">
<div class="twelve wide column">
  <div class="ui fluid raised card" id="chat">
  <div class="content">
  <div class="ui small feed">
    <h4 class="ui header">Followers Activity</h4>
    <% @messages.each do |i| %>
        <div class="event">
          <div class="content">
            <div class="summary">
           <h3><%= i.user.username %>:<%= i.body %></h3>
              
            </div>
          </div>
        </div>
    <% end %>    
        
  </div>
  </div>

  <div class="extra content">
  <%= form_for(@message,html: {class: "ui reply form", role: "form"},url: message_path) do |f| %>
        <div class="field">
          <%= f.text_field :body %>
        </div>
        <div class="ui icon">
          <%= f.submit 'Send',class: "ui inverted orange button" %> 
        </div>
  <% end %>

  </div>

  </div>
</div>



<div class="four wide column">
<div class="ui fluid raised card">
<div class="content">
<div class="ui inverted vertical pointing menu">
  <a class="active item">
    Home
  </a>
  <a class="item">
    Messages
  </a>
  <a class="item">
    Friends
  </a>
</div>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CHATAPPLICATION</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <div class="ui small inverted menu">
  <div class="ui container" align="center">
  <a class="active item">
    Chatroom
  </a>
  <a class="item">
    Messages
  </a>
  <div class="right menu">
    <div class="ui dropdown item">
      Account <i class="dropdown icon"></i>
      <div class="menu">
      <%= link_to 'Login',login_path,class: "item" %>
      <%= link_to 'Logout',login_path,class: "item" %>
      
      </div>
    </div>
    <div class="item">
        <div class="ui primary button">Sign Up</div>
    </div>
  </div>
</div>
</div>

<div class="ui container" align="center">
    <%= yield %>
</div>    
  </body>
</html>